### ISSUE TITLE
Decoded message is not valid

### ISSUE THREAD

**Issue by sholtomaud** [digidem/hyperdb-sneakernet#2]
I'm not sure what the source of this error is ...
Any thoughts?
```
hyperdb-sneakernet/node_modules/hyperdb/lib/messages.js:117

if (!found0 || !found2) throw new Error("Decoded message is not valid")
```

**Comment by hackergrrl** [comment]
How are you using the module? Can you reproduce the problem with a small amount of code?

**Comment by sholtomaud** [comment]
Sorry I didn't get back to you. I've just done a fresh download and I didn't get this issue.
